version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: