version: '3.7'

services:
  ruffle_web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  ruffle_api:
    container_name: ruffle_api
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    env_file:
      - ./api/.env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      DB_HOST: mongodb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SERVICE_PORT: ${SERVICE_PORT}
      JWT_SECRET: ${JWT_SECRET}
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
